const fonts = ["Lobster",
    "Lemonada",
    "Odibee Sans",
    "Modak",
    "Galada",
    "Righteous",
    "Patua One",
    "Luckiest Guy",
    "Passion One",
    "Alfa Slab One",
    "Bangers",
    "Baloo Bhai",
    "Sigmar One",
    "PLayball",
    "Chewy",
    "Black Ops One",
    "Boogaloo",
    "Shrikhand",
    "Racing Sans One",
    "Shojumaru",
    "Bungee",
    "Graduate",
    "Turret Road",
    "McLaren",
    "Spicy Rice",
    "Limelight",
    "Bowlby One",
    "Ranchers",
    "Creepster",
    "Ewert",
    "Peralta",
    "Germania One",
    "Sarina",
    "Trade Winds",
    "Pirata One",
    "Uncial Antiqua",
    "Smokum",
    "Iceberg",
    "Caesar Dressing",
    "Mrs Sheppards",
    "Permanent Marker",
    "Marck Script",
    "Yellowtail",
    "VT323",
    "Oswald",
    "Anton",
    "Arvo",
    "Acme",
    "Monsterrat Subrayada",
]

export default fonts